{
    "subject": "Anonymized unique identifier for the subject",
    "release": "HBN Release number which this subject appeared in",
    "task": "Name of the EEG task",
    "availability": "Quality assessment of EEG recording given by the HBN-EEG dataset",
    "eeg_samples": "Number of samples in the EEG recording",
    "et_samples": "Number of samples in the ET recording",
    "eeg_sampling_rate_hz": "Sampling rate of EEG recording",
    "et_sampling_rate_hz": "Estimated sampling rate of ET recording",
    "eeg_samples_trimmed": "Number of OOB EEG samples (dropped on realignment)",
    "et_samples_trimmed": "Number of OOB ET samples (dropped on realignment)",
    "eeg_nan_values": "Number of invalid EEG samples",
    "et_nan_values": "Number of invalid ET samples (most channels set to 0)",
    "eeg_channel_cnt": "Number of EEG channels",
    "et_channel_cnt": "Number of ET channels",
    "et_has_PORX": "ET has channel 'L POR X [px]' and 'R POR X [px]' ",
    "et_data_format": "File ending of the ET recording",
    "et_has_eventfile": "Does ET recording include a second file *_Events.txt?",
    "et_eventfile_matches": "Do annotations of the regular ET file and *_Events file match?",
    "et_unknown_events": "Number of Lines in ET recording that could not be parsed (usually headers)",
    "shared_events": "Number of events to be synced on (appear in ET and EEG)",
    "mean_abs_sync_error_ms": "",
    "within_1_sample": "",
    "within_4_samples": "",
    "regression_slope": "",
    "regression_intercept": "",
    "xcorr_zero": "",
    "xcorr_peak": "",
    "xcorr_peak_idx": "",
    "xcorr_second_peak": "",
    "xcorr_second_peak_idx": "",
    "snr": "",
    "xcorr_cosine_similarity": "",
    "xcorr_rmse": "",
    "xcorr_dinf": "",
    "xcorr_scale": "",
    "xcorr_kl": "",
    "n_saccades": "",
    "avg_saccade_amplitude": "",
    "avg_saccade_duration_ms": "",
    "avg_fixation_duration_ms": "",
    "n_blinks": "",
    "avg_blink_duration_ms": "",
    "et_sfreq_est": "",
    "xcorr_peak_prominence": "",
    "xcorr_second_peak_prominence": "",
    "xcorr_template_steepness_left": "",
    "xcorr_template_steepness_right": "",
    "xcorr_n_peaks_spike": "",
    "xcorr_kurtosis": "",
    "xcorr_kurtosis_weighted": "",
    "xcorr_zero_norm": "",
    "xcorr_peak_norm": "",
    "xcorr_peak_idx_norm": "",
    "xcorr_peak_prominence_norm": "",
    "xcorr_second_peak_norm": "",
    "xcorr_second_peak_idx_norm": "",
    "xcorr_second_peak_prominence_norm": "",
    "xcorr_cosine_similarity_norm": "",
    "xcorr_rmse_norm": "",
    "xcorr_dinf_norm": "",
    "xcorr_template_steepness_left_norm": "",
    "xcorr_template_steepness_right_norm": "",
    "xcorr_n_peaks_spike_norm": "",
    "xcorr_kurtosis_norm": "",
    "xcorr_kurtosis_weighted_norm": "",
    "et_sfreq_avg": "",
    "et_eventfile_matches_filtered": ""
}